package com.halykmarket.merchant.telegabot.enums;

public enum WaitingType {
    START,
    SET_FULL_NAME, SET_PHONE_NUMBER, PHOTO,
    SET_WEIGHT, SET_WAIST, SET_AD, SET_CSS, SET_RHYTHM, SET_FK, SET_THERAPY, SET_INFORMATION, SET_TYPE_REGISTRATION,
    WRITE_COME_DATE, WRITE_OUT_DATE, WRITE_COME_TIME, WRITE_OUT_TIME;
}
